name: Build and Release

on:
  push:
    tags:
      - "v*"   # Trigger workflow on tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Change if using another version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release

      - name: Publish build (to get exe)
        run: dotnet publish -c Release -o published

      - name: Create zip
        run: Compress-Archive -Path published\* -DestinationPath MyApp-${{ github.ref_name }}.zip

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: MyApp-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
